name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        # env: # Set the repo secret as an input
        #   MY_NAME: ${{ env.TEST }}
        with: # Set the repo secret as an input
          MY_NAME: ${{ env.TEST }}
        # with:
        #   MY_NAME: "Bram"