name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with: # Set the secret as an input
          MY_NAME: ${{ secrets.test }}
        # with:
        #   MY_NAME: "Bram"